import 'package:flutter/material.dart';
import 'package:get/get.dart';

class SupplierHelpScreen extends StatelessWidget {
  const SupplierHelpScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Help'),
          backgroundColor: Get.theme.colorScheme.primary,
          leading: IconButton(
            icon: Icon(
              Icons.arrow_back,
            ),
            onPressed: () {
              Get.back();
            },
          ),
          elevation: 0,
        ),
        body: ListView.builder(
          itemBuilder: (BuildContext context, int index) =>
              EntryItem(data[index]),
          itemCount: data.length,
        ),
      ),
    );
  }
}

class Entry {
  Entry(this.title, [this.children = const <Entry>[]]);

  final String title;
  final List<Entry> children;
}

final List<Entry> data = <Entry>[
  Entry(
    'Authentication ',
    <Entry>[
      Entry(
        'In order to use the application, the user needs to create his/her account in the app. On registration form for security purpose whenever we register for first time you need to fill OTP i.e One Time Password which is autogenerated if you have same number sim with you otherwise you need to fill manually within 2 min . You can resend it if time limit ends from Bottom Resend option. You need to go through same  process for both Donor and NGO side. Both restaurant and users who have the food must register using registration form. During registration, some information about the users is saved to the real-time database such as address, name and gender under the unique user id. So, each user profile information is saved into the database and next time user can directly jump to there profile and edit the information. ',
      ),
    ],
  ),
  Entry('About your donation', <Entry>[
    Entry(
      'Donate now and Help To Save Lives by providing hungry children and Families Nutritious meals. Donate to provide Nutritious food for hungry. If u want to donate the food you need to fill registration form in which you provide yours details like name meal category, meal packaging, donation reasons and description of meal. In order to donate food you have to select location of your donation. After submitting the donate food form it will be shown on dashboard with status pending until NGO accept it.',
    ),
  ]),
  Entry('History', <Entry>[
    Entry(
      'Once you donate your food and it’s completed successfully then History will be showing on your dashboard as well as History tab so you can hold your history. If Food is not delivered to NGO’s within time limit whatever you are mentioned then food is Expired and it will be shown in History tab.',
    ),
  ]),
  Entry('List of NGOs', <Entry>[
    Entry(
      'On NGOs tab you will be showing all list of NGOs registered in the application. On tapping on more button, you will be able to see the details of the particular NGO.',
    ),
  ]),
  Entry('Profile', <Entry>[
    Entry(
      'On the profile tab, you will be able to see your profile, if you wish you can update your profile.',
    ),
  ]),
];

class EntryItem extends StatelessWidget {
  // ignore: use_key_in_widget_constructors
  const EntryItem(this.entry);

  final Entry entry;

  Widget _buildTiles(Entry root) {
    if (root.children.isEmpty) return ListTile(title: Text(root.title));
    return ExpansionTile(
      key: PageStorageKey<Entry>(root),
      title: Text(root.title),
      children: root.children.map(_buildTiles).toList(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return _buildTiles(entry);
  }
}
